version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: my-app-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: qa_with_personas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d qa_with_personas" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build: ./backend
    container_name: my-app-backend
    environment:
      NODE_ENV: development
      DB_USERNAME: myuser
      DB_HOST: db
      DB_NAME: qa_with_personas
      DB_PASSWORD: "123"
      DB_PORT: 5432
      PORT: 5000
      FRONTEND_URL: http://localhost:5173
      FRONTEND_PORT: 5173
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run start:dev

  # Frontend React App
  frontend:
    build: ./frontend
    container_name: my-app-frontend
    environment:
      - VITE_API_BASE_URL=http://localhost:5000
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    command: npm run dev -- --host 0.0.0.0 --port 5173

volumes:
  postgres_data:
